## Упражнения по библиотеке Numpy

In [1]:
import numpy as np

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

**1.** Given a random array, change the sign of the elements whose values are between 3 and 8

In [2]:
# your code
arr = np.random.randint(1, 10, 20)
arr[(arr >= 3) & (arr <= 8)] *= -1
print(arr)

[-6 -8 -6 -7  2 -4 -8  9 -3  1 -6  1  2  1 -7 -7  1 -6  2 -8]


**2.** Заменить максимальный элемент случайного массива на 0

**2.** Replace the maximum element of a random array with 0

In [3]:
# your code
arr[arr == arr.max()] = 0

**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

**3.** Construct the Cartesian product of the arrays (all combinations of every element). The input is a two-dimensional array

In [ ]:
# your code
arr = np.random.randint(1, 100, 15).reshape(3, 5)
print(arr)
grid = np.meshgrid(*arr)
cartesian_product = np.column_stack([g.ravel() for g in grid])
print(cartesian_product)

[[22 94 91 89 74]
 [65 68 56 83 23]
 [15 19  9 97  5]]
[[22 65 15]
 [22 65 19]
 [22 65  9]
 [22 65 97]
 [22 65  5]
 [94 65 15]
 [94 65 19]
 [94 65  9]
 [94 65 97]
 [94 65  5]
 [91 65 15]
 [91 65 19]
 [91 65  9]
 [91 65 97]
 [91 65  5]
 [89 65 15]
 [89 65 19]
 [89 65  9]
 [89 65 97]
 [89 65  5]
 [74 65 15]
 [74 65 19]
 [74 65  9]
 [74 65 97]
 [74 65  5]
 [22 68 15]
 [22 68 19]
 [22 68  9]
 [22 68 97]
 [22 68  5]
 [94 68 15]
 [94 68 19]
 [94 68  9]
 [94 68 97]
 [94 68  5]
 [91 68 15]
 [91 68 19]
 [91 68  9]
 [91 68 97]
 [91 68  5]
 [89 68 15]
 [89 68 19]
 [89 68  9]
 [89 68 97]
 [89 68  5]
 [74 68 15]
 [74 68 19]
 [74 68  9]
 [74 68 97]
 [74 68  5]
 [22 56 15]
 [22 56 19]
 [22 56  9]
 [22 56 97]
 [22 56  5]
 [94 56 15]
 [94 56 19]
 [94 56  9]
 [94 56 97]
 [94 56  5]
 [91 56 15]
 [91 56 19]
 [91 56  9]
 [91 56 97]
 [91 56  5]
 [89 56 15]
 [89 56 19]
 [89 56  9]
 [89 56 97]
 [89 56  5]
 [74 56 15]
 [74 56 19]
 [74 56  9]
 [74 56 97]
 [74 56  5]
 [22 83 15]
 [22 83 19]
 [22 83  9]
 [22 83 9

**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

**4.** Given two arrays, A (8×3) and B (2×2). Find the rows in A that contain at least one element from each row of B, regardless of the order of elements in B.

In [21]:
# your code
arrA = np.random.randint(1, 20, 24).reshape(8, 3)
arrB = np.random.randint(1, 20, 4).reshape(2, 2)
print(arrA)
print(arrB)

first_row = np.isin(arrA, arrB[0])
second_row = np.isin(arrA, arrB[1])

contains = np.any(first_row, axis=1) & np.any(second_row, axis=1)
print(arrA[contains])

[[ 7 11  9]
 [ 3 17  4]
 [ 7 12  2]
 [ 1 11 15]
 [ 6 11  4]
 [ 9  6  9]
 [ 9  5  7]
 [ 2 18 10]]
[[ 7 18]
 [10 11]]
[[ 7 11  9]
 [ 2 18 10]]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

5. Given a 10×3 matrix, find the rows consisting of unequal values (for example, row [2, 2, 3] remains, row [3, 3, 3] is removed).

In [ ]:
# your code
arr = np.random.randint(1, 5, 30).reshape(10, 3)
print(arr)
unequal_rows = arr[~((arr[:, 0] == arr[:, 1]) & (arr[:, 0] == arr[:, 2]))]
print(unequal_rows)  

[[2 4 4]
 [3 1 2]
 [3 3 3]
 [2 2 3]
 [3 1 3]
 [3 4 3]
 [2 1 1]
 [3 2 3]
 [2 3 2]
 [1 3 4]]
[[2 4 4]
 [3 1 2]
 [2 2 3]
 [3 1 3]
 [3 4 3]
 [2 1 1]
 [3 2 3]
 [2 3 2]
 [1 3 4]]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

6. Given a two-dimensional array. Delete the rows that are repeated.

In [7]:
# your code
arr = np.random.randint(1, 5, 20).reshape(10, 2)
print(f"ORIGINAL ARRAY\n{arr}\n")
print(f"REMOVE DUPLICATES\n{np.unique(arr, axis=0)}\n")

ORIGINAL ARRAY
[[2 2]
 [2 3]
 [1 2]
 [3 2]
 [3 2]
 [1 3]
 [4 4]
 [4 2]
 [2 1]
 [2 4]]

REMOVE DUPLICATES
[[1 2]
 [1 3]
 [2 1]
 [2 2]
 [2 3]
 [2 4]
 [3 2]
 [4 2]
 [4 4]]



______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

For each of the following tasks (1-5), you must provide 2 implementations:

Without using NumPy: Assume that where a NumPy array should be used for input or output, it will simply be a standard Python list.

Fully vectorized using NumPy: Do not use Python loops, map, or list comprehensions.

Remark 1: You may assume that all specified objects are non-empty (for example, in Task 1, the diagonal of the matrix contains non-zero elements).

Remark 2: For most tasks, the solution takes no more than 1–2 lines of code.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

- Task 1: Calculate the product of the non-zero elements on the diagonal of a rectangular matrix. For example, for X=np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]), the answer is 3.

In [40]:
# your code
# WITHOUT NUMPY
x = [[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]
prod = 1
diag = [x[i][i] for i in range(min(len(x), len(x[0])))]
for num in diag:
    if num != 0: prod *= num
print(prod)

# WITH NUMPY
x = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])
diag = np.diag(x)
print(np.prod(diag[diag!=0]))

3
3


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

- Task 2: Given two vectors x and y. Check if they define the same multiset. For example, for x=np.array([1, 2, 2, 4]) and y=np.array([4, 2, 1, 2]), the answer is True.

In [51]:
# your code
# WITHOUT NUMPY
x = [1, 2, 2, 4]
y = [4, 2, 1, 2]
x_uniques = sorted(list(set(x)))
x_uniques_count = [x.count(i) for i in x_uniques]
y_uniques = sorted(list(set(y)))
y_uniques_count = [y.count(i) for i in y_uniques]
print((x_uniques == y_uniques) and (x_uniques_count == y_uniques_count))

# WITH NUMPY
x = np.array([1, 2, 2, 4])
y = np.array([4, 2, 1, 2])
x_uniques, x_uniques_count = np.unique(x, return_counts=True)
y_uniques, y_uniques_count = np.unique(y, return_counts=True)
print(len(x_uniques) == len(y_uniques) and np.all(x_uniques_count == y_uniques_count))

True
True


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

- Task 3: Find the maximum element in vector x among the elements that are preceded by a zero. For example, for x=np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]), the answer is 5.

In [63]:
# your code
# WITHOUT NUMPY
x = [6, 2, 0, 3, 0, 0, 5, 7, 0]
zero_preceded = [x[i] for i in range(1, len(x)) if x[i-1] == 0]
print(max(zero_preceded))

# WITH NUMPY
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
zero_preceded = np.argwhere(x == 0) + 1
print(np.max(x[zero_preceded[zero_preceded < len(x)]]))

5
5


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

- Task 4: Implement Run-length encoding (RLE). For a given vector x, return a tuple of two vectors of equal length. The first vector contains the values, and the second contains the number of times each value is repeated consecutively. For example, for x=np.array([2, 2, 2, 3, 3, 3, 5]), the answer is (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [ ]:
# your code
# WITHOUT NUMPY
x = [2, 2, 2, 3, 3, 3, 5]
x_elem = []
x_elem_counts = []
count = 1
for i in range(len(x)):
    if (i + 1 < len(x)) and (x[i] == x[i+1]):
        count += 1
    else:
        x_elem.append(x[i])
        x_elem_counts.append(count)
        count = 1
print(x_elem, x_elem_counts)

# WITH NUMPY
x = np.array([2, 2, 2, 3, 3, 3, 5])
mask = x[1:] != x[:-1]
split_ind = np.concatenate(([0], np.where(mask)[0] + 1, [len(x)]))
print(x[split_ind[:-1]], np.diff(split_ind))


[2, 3, 5] [3, 3, 1]
[2 3 5] [3 3 1]


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

- Task 5: Given two sets of objects, X and y. Calculate the matrix of Euclidean distances between the objects. Compare your implementation with the scipy.spatial.distance.cdist function in terms of execution speed.

In [120]:
# your code
import math
from scipy.spatial.distance import cdist
import time
# WITHOUT NUMPY
wo_np_start = time.time()
x = [[1, 2], [0, 3], [4, 6]]
y = [[2, 2], [3, 5]]
euclidean_distances = []

for point_x in x:
    for point_y in y:
        euclidean_distances.append(math.sqrt(pow((point_y[0]-point_x[0]), 2) + pow((point_y[1]-point_x[1]), 2)))
print(euclidean_distances)
wo_np_end = time.time()
print(f"\nExecution time for without numpy: {wo_np_end - wo_np_start}\n")

# WITH NUMPY
w_np_start = time.time()
x = np.array([[1, 2], [0, 3], [4, 6]])
y = np.array([[2, 2], [3, 5]])
x_grid = np.repeat(x, len(y), axis=0)
y_grid = np.tile(y, (len(x), 1))
diffs = y_grid - x_grid
print(np.linalg.norm(diffs, axis=1))
w_np_end = time.time()
print(f"\nExecution time for with numpy: {w_np_end - w_np_start}\n")

# WITH cdist
w_cdist_start = time.time()
print(cdist(x, y))
w_cdist_end = time.time()
print(f"\nExecution time with cdist: {w_cdist_end - w_cdist_start}\n")


[1.0, 3.605551275463989, 2.23606797749979, 3.605551275463989, 4.47213595499958, 1.4142135623730951]

Execution time for without numpy: 0.0001480579376220703

[1.         3.60555128 2.23606798 3.60555128 4.47213595 1.41421356]

Execution time for with numpy: 0.00024890899658203125

[[1.         3.60555128]
 [2.23606798 3.60555128]
 [4.47213595 1.41421356]]

Execution time with cdist: 0.0003371238708496094



_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [13]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

1. Review the file cereal.csv. This file contains calorie counts for various cereal brands. Load the data from the file and save it as calorie_stats

In [14]:
calorie_stats = np.loadtxt("/Users/niako/Innowise/Task4_NumPy_Pandas/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

2. One serving of CrunchieMunchies contains 60 calories. How much higher is the average calorie count of your competitors? Save the answer in a variable named average_calories and print the variable to the terminal.

In [15]:
# your code
average_calories = np.mean(calorie_stats)
print(f"The difference is {average_calories - 60} calories")
average_calories

The difference is 46.883116883116884 calories


np.float64(106.88311688311688)

3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

3. Does the average calorie count correctly reflect the distribution of the dataset? Let’s sort the data and see.

Sort the data and save the result in a variable named calorie_stats_sorted. Print the sorted information.

In [16]:
# your code
calorie_stats_sorted = np.sort(calorie_stats)
calorie_stats_sorted

array([ 50.,  50.,  50.,  70.,  70.,  80.,  90.,  90.,  90.,  90.,  90.,
        90.,  90., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 120., 120., 120., 120., 120., 120., 120.,
       120., 120., 120., 130., 130., 140., 140., 140., 150., 150., 160.])

4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

4. It looks like most values are above the average. Let’s see if the median is a more accurate indicator for the dataset.

Calculate the median of the dataset and save your answer in median_calories. Print the median so you can see how it compares to the average value.

In [17]:
# your code
median_calories = np.median(calorie_stats_sorted)
median_calories

np.float64(110.0)

5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

5. While the median shows that at least half of the values are over 100 calories, it would be more impressive to show that a significant portion of competitors have a higher calorie count than CrunchieMunchies.

Calculate various percentiles and print them until you find the lowest percentile that is greater than 60 calories. Save this value in the variable nth_percentile.

In [18]:
# your code
np.percentile(calorie_stats_sorted, 3) # 55.599999 < 60
np.percentile(calorie_stats_sorted, 4) # 70 > 70
nth_percentile = 4

6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

6. Although the percentile shows us that most competitors have a much higher calorie count, it is an awkward concept to use in marketing materials.

Instead, let’s calculate the percentage of cereals that contain more than 60 calories per serving. Save your answer in a variable named more_calories and print it.

In [19]:
# your code
more_calories = 100 - nth_percentile
more_calories

# or manual way
# more_calories = len(calorie_stats_sorted[calorie_stats_sorted > 60]) * 100 / len(calorie_stats_sorted)

96

7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

7. That is a truly high percentage. This will be very useful when we promote CrunchieMunchies. But one question remains: how large are the variations in the dataset? Can we generalize that most cereals contain around 100 calories, or is the spread even wider?

Calculate the amount of variation by finding the standard deviation. Save your answer in calorie_std and print it to the terminal. How can we include this value in our analysis?

In [20]:
# your code
calorie_std = np.std(calorie_stats_sorted)
calorie_std

np.float64(19.35718533390827)

8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

8. Write a short paragraph summarizing your findings and how you believe this data could be used in Mycrunch's interest when marketing CrunchieMunchies.

In [21]:
# your code
